### ISSUE TITLE
joint mode

### ISSUE THREAD

**Issue by wammar** [karlmoritz/bicvm#4]
Hi Karl,

Great work! Thanks for making this available!

I'm trying to train word embeddings for more than two languages in the same vector space (i.e., the joint mode in section 5.3 of the ACL 2014), but the interface appears to only allow for specifying parallel sentences/documents for one language pair. I realize you've done a lot of changes to the code since the paper was published so I wonder if it's still possible to train the model in the joint mode?

Thank you,
waleed ammar

**Comment by karlmoritz** [comment]
Hi Waleed,

The easiest way to do this is to add substrings to all words per language
(i.e. dog_en, hund_de, chien_fr). If you have only bilingually aligned data
with a single source language (as I did in the paper), then you can have
the source language on one side, the other languages in the second input
file. If you have multiple alignments across multiple languages you may
want to modify the code so that both embeddings share one space directly --
I think that should be a fairly simple change to the current code.
